version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ~/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/app/nginx/conf.d:/etc/nginx/conf.d
      - ~/app/nginx/logs:/var/log/nginx
      - ~/app/nginx/ssl:/etc/ssl
    ports:
      - "9001:9002"
      - "5001:5000"
    depends_on:
      - id_allocation
      - cryptodata_apollographql
    networks:
      put_net:
        ipv4_address: 192.168.100.2

  id_allocation:
    image: ghcr.io/zhongfuze/id_allocation:main
    container_name: id_allocation
    volumes:
      - ~/app/id_allocation/data:/app/data
      - ~/app/id_allocation/config:/app/config
      - ~/app/id_allocation/log_tmp:/tmp
      - ~/app/id_allocation/log:/app/log
    ports:
      - "9002:9002"
    networks:
      put_net:
        ipv4_address: 192.168.100.3

  cryptodata_apollographql:
    image: ghcr.io/zhongfuze/cryptodata_apollographql:main
    container_name: cryptodata_apollographql
    volumes:
      - ~/app/cryptodata_apollographql/data:/app/data
      - ~/app/cryptodata_apollographql/config:/app/config
      - ~/app/cryptodata_apollographql/log_tmp:/tmp
      - ~/app/cryptodata_apollographql/log:/app/log
    ports:
      - "5000:5000"
    networks:
      put_net:
        ipv4_address: 192.168.100.4

networks:
  put_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24